name: RSS Parser

on:
  schedule:
    - cron: "*/5 * * * *"
  push:
    branches:
      - main  # 或其他你想要触发的分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  # 选择你想要使用的Python版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install feedparser

    - name: Run RSS Parser
      run: python parse_rss.py > rss_output.txt
